site_name: Flarelette JWT Kit
site_description: Environment-driven JWT authentication for Cloudflare Workers
site_author: Chris Lyons
site_url: https://chrislyons-dev.github.io/flarelette-jwt-kit/

repo_name: chrislyons-dev/flarelette-jwt-kit
repo_url: https://github.com/chrislyons-dev/flarelette-jwt-kit
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 Chris Lyons

theme:
  name: material
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chrislyons-dev/flarelette-jwt-kit
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
      - Core Concepts: core-concepts.md
      - Usage Guide: usage-guide.md
      - Service Delegation: service-delegation.md
  - Deployment:
      - Cloudflare Workers: cloudflare-workers.md
  - Security:
      - Security Guide: security-guide.md
