
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flarelette-jwt-kit"
version = "1.4.0"
description = "Unified JWT sign/verify, auth helpers, and secret generator for Flarelette ecosystem (Python + Node) — HS512 default"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Chris Lyons", email = "dev@chrislyons.dev" }]
requires-python = ">=3.11"
dependencies = []
