@startuml
set separator none
title flarelette-jwt-kit - flarelette-jwt - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  defaultFontName "Arial"
}

hide stereotype

skinparam rectangle<<flarelettejwtkit.flarelettejwt.adaptersapply_env_bindings>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<flarelettejwtkit.flarelettejwt>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

rectangle "flarelette-jwt\n<size:10>[Container: Service]</size>" <<flarelettejwtkit.flarelettejwt>> {
  rectangle "==adapters.apply_env_bindings\n<size:10>[Component: function]</size>\n\nCopy a Cloudflare Worker `env` mapping into os.environ so the kit can read it." <<flarelettejwtkit.flarelettejwt.adaptersapply_env_bindings>> as flarelettejwtkit.flarelettejwt.adaptersapply_env_bindings
}

@enduml