graph LR
  linkStyle default fill:#ffffff

  subgraph diagram [" "]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 1 [" "]
      style 1 fill:#ffffff,stroke:#0b4884,color:#0b4884

      2("<div style='font-weight: bold'>@chrislyons-dev/flarelette-jwt</div><div style='font-size: 70%; margin-top: 0px'>[Container: Service]</div><div style='font-size: 80%; margin-top:10px'>TypeScript implementation of<br />the Flarelette JWT Kit: An<br />environment-driven JWT<br />authentication package for<br />Cloudflare Workers</div>")
      style 2 fill:#438dd5,stroke:#2e6295,color:#ffffff
      61("<div style='font-weight: bold'>flarelette-jwt</div><div style='font-size: 70%; margin-top: 0px'>[Container: Service]</div><div style='font-size: 80%; margin-top:10px'>Python implementation of the<br />Flarelette JWT Kit: An<br />environment-driven JWT<br />authentication package for<br />Cloudflare Workers</div>")
      style 61 fill:#438dd5,stroke:#2e6295,color:#ffffff
    end

  end