graph LR
  linkStyle default fill:#ffffff

  subgraph diagram [" "]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 2 [" "]
      style 2 fill:#ffffff,stroke:#2e6295,color:#2e6295

      55("<div style='font-weight: bold'>adapters.bindEnv</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Store both environment<br />variables and service<br />bindings globally</div>")
      style 55 fill:#d4e8fc,stroke:#94a2b0,color:#000000
      56("<div style='font-weight: bold'>adapters.getServiceBinding</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Get service binding by name<br />from global storage</div>")
      style 56 fill:#d4e8fc,stroke:#94a2b0,color:#000000
      57("<div style='font-weight: bold'>adapters.makeKit</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Returns a namespaced kit<br />whose calls use the provided<br />env bag. Automatically<br />injects JWKS service binding<br />if configured.</div>")
      style 57 fill:#d4e8fc,stroke:#94a2b0,color:#000000
    end

  end