graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["flarelette-jwt-kit - @chrislyons-dev/flarelette-jwt - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 2 ["@chrislyons-dev/flarelette-jwt"]
      style 2 fill:#ffffff,stroke:#2e6295,color:#2e6295

      41("<div style='font-weight: bold'>adapters.bindEnv</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Store both environment<br />variables and service<br />bindings globally</div>")
      style 41 fill:#85bbf0,stroke:#5d82a8,color:#000000
      42("<div style='font-weight: bold'>adapters.getServiceBinding</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Get service binding by name<br />from global storage</div>")
      style 42 fill:#85bbf0,stroke:#5d82a8,color:#000000
      43("<div style='font-weight: bold'>adapters.makeKit</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Returns a namespaced kit<br />whose calls use the provided<br />env bag. Automatically<br />injects JWKS service binding<br />if configured.</div>")
      style 43 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end