graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["flarelette-jwt-kit - flarelette-jwt - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 33 ["flarelette-jwt"]
      style 33 fill:#ffffff,stroke:#2e6295,color:#2e6295

      36("<div style='font-weight: bold'>flarelette-jwt-py.on_fetch</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Handle incoming requests for<br />testing.</div>")
      style 36 fill:#85bbf0,stroke:#5d82a8,color:#000000
      37("<div style='font-weight: bold'>flarelette-jwt-py.PKG_DIR</div><div style='font-size: 70%; margin-top: 0px'>[Component: type]</div>")
      style 37 fill:#85bbf0,stroke:#5d82a8,color:#000000
      38("<div style='font-weight: bold'>flarelette-jwt-py.DOCS_DIR</div><div style='font-size: 70%; margin-top: 0px'>[Component: type]</div>")
      style 38 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end