@startuml
set separator none
title flarelette-jwt-kit - flarelette-jwt - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  defaultFontName "Arial"
}

hide stereotype

skinparam rectangle<<flarelettejwtkit.flarelettejwt.flarelettejwtpyDOCS_DIR>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<flarelettejwtkit.flarelettejwt.flarelettejwtpyPKG_DIR>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<flarelettejwtkit.flarelettejwt.flarelettejwtpyon_fetch>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<flarelettejwtkit.flarelettejwt>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

rectangle "flarelette-jwt\n<size:10>[Container: Service]</size>" <<flarelettejwtkit.flarelettejwt>> {
  rectangle "==flarelette-jwt-py.on_fetch\n<size:10>[Component: function]</size>\n\nHandle incoming requests for testing." <<flarelettejwtkit.flarelettejwt.flarelettejwtpyon_fetch>> as flarelettejwtkit.flarelettejwt.flarelettejwtpyon_fetch
  rectangle "==flarelette-jwt-py.PKG_DIR\n<size:10>[Component: type]</size>" <<flarelettejwtkit.flarelettejwt.flarelettejwtpyPKG_DIR>> as flarelettejwtkit.flarelettejwt.flarelettejwtpyPKG_DIR
  rectangle "==flarelette-jwt-py.DOCS_DIR\n<size:10>[Component: type]</size>" <<flarelettejwtkit.flarelettejwt.flarelettejwtpyDOCS_DIR>> as flarelettejwtkit.flarelettejwt.flarelettejwtpyDOCS_DIR
}

@enduml