name = "bond-consumer"
main = "examples/eddsa.consumer.example.ts"
compatibility_date = "2025-10-01"

[vars]
# Indirection: name -> actual URL binding
JWT_JWKS_URL_NAME = "GW_JWKS_URL"
GW_JWKS_URL = "https://gateway.internal/.well-known/jwks.json"

# Standard claim expectations
JWT_ISS = "https://gateway.internal"
JWT_AUD = "bond-math.api"

# Optional pinning (comma-separated JWK thumbprints)
# JWT_ALLOWED_THUMBPRINTS = "thumb1,thumb2"
