# EdDSA JWT Producer (Gateway) Configuration
#
# This worker serves dual roles:
#   1. Signs JWTs using Ed25519 private key
#   2. Exposes JWKS endpoint for consumer workers via service binding
#
# Setup:
#   1. Generate keypair:
#      npx flarelette-jwt-keygen --kid=ed25519-2025-01 > keys.json
#
#   2. Store private key as secret:
#      wrangler secret put GW_ED25519_PRIVATE --config examples/eddsa.producer.example.toml
#      (paste the privateJwk JSON from keys.json)
#
#   3. Copy publicJwk to GW_ED25519_PUBLIC below (replace <paste-public-jwk-here>)
#
#   4. Deploy:
#      wrangler deploy --config examples/eddsa.producer.example.toml
#
# Consumer workers bind to this via [[services]] configuration.

name = "jwt-gateway"
main = "examples/eddsa.producer.example.ts"
compatibility_date = "2025-10-01"

[vars]
# Secret name indirection (points to wrangler secret)
JWT_PRIVATE_JWK_NAME = "GW_ED25519_PRIVATE"

# Key ID (must match kid in JWK)
JWT_KID = "ed25519-2025-01"

# Token claims
JWT_ISS = "https://gateway.internal"
JWT_AUD = "api.internal"
JWT_TTL_SECONDS = "900"  # 15 minutes

# Public key for JWKS endpoint (paste publicJwk from keys.json)
# Example format: {"kty":"OKP","crv":"Ed25519","kid":"ed25519-2025-01","x":"<base64url>","alg":"EdDSA","use":"sig"}
GW_ED25519_PUBLIC = '<paste-public-jwk-here>'

# Alternative: Use secret binding for public key too
# JWT_PUBLIC_JWK_NAME = "GW_ED25519_PUBLIC"
# Then: wrangler secret put GW_ED25519_PUBLIC

# Secrets (set via wrangler secret put)
# GW_ED25519_PRIVATE - Ed25519 private key (JSON)
