[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flarelette-jwt"
version = "1.8.0"
description = "Environment-driven JWT authentication for Cloudflare Workers Python with secret-name indirection"
readme = "docs/README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [{ name = "Chris Lyons", email = "chris@chrislyons.dev" }]
keywords = [
    "jwt",
    "authentication",
    "cloudflare",
    "workers",
    "edge",
    "hs512",
    "eddsa",
    "ed25519",
    "pyodide",
    "flarelette",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Security",
]
dependencies = ["setuptools"]

[project.urls]
Homepage = "https://github.com/chrislyons-dev/flarelette-jwt-kit"
Repository = "https://github.com/chrislyons-dev/flarelette-jwt-kit"
Issues = "https://github.com/chrislyons-dev/flarelette-jwt-kit/issues"
Documentation = "https://github.com/chrislyons-dev/flarelette-jwt-kit#readme"

[project.scripts]
flarelette-jwt-secret = "flarelette_jwt.secret:main"
