
[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "flarelette-jwt-py"
version = "1.4.0"
description = "JWT sign/verify, auth helpers, and secret generator for Python Cloudflare Workers — HS512 default"
authors = [{ name = "Chris Lyons" }]
requires-python = ">=3.11"
dependencies = []
license = { text = "MIT" }

[project.scripts]
flarelette-jwt-secret = "flarelette_jwt.secret:main"
